# Chart metadata
name: hello-python
version: 0.1.0
# Chart dependencies
dependencies: []
# Chart values
values:
  # Image repository and tag
  image:
    repository: ghcr.io/confusb/hello-python
    tag: 2
  # Container port
  port: 80
  # Service type
  service:
    type: ClusterIP
# Chart templates
templates:
  # Deployment template
  deployment.yaml:
    # Deployment metadata
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hello-python
    # Deployment spec
    spec:
      # Number of replicas
      replicas: 1
      # Pod template
      template:
        # Pod metadata
        metadata:
          labels:
            app: hello-python
        # Pod spec
        spec:
          # Container spec
          containers:
            - name: hello-python
              # Container image
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              # Container port
              ports:
                - containerPort: 80
# Service template
service.yaml:
  # Service metadata
  apiVersion: v1
  kind: Service
  metadata:
    name: hello-python-service
  # Service spec
  spec:
    # Service type
    type: ClusterIP #{{ .Values.service.type }}
    # Service selector
    selector:
      app: hello-python
    # Service ports
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80 # {{ .Values.port }}
