# This is a YAML-formatted workflow file
name: Build and push Docker image

# Triggers the workflow on push events to the master branch
on:
  push:
    branches:
      - feat/cicd

# Defines a set of jobs that can run concurrently
jobs:
  # Defines a job called "build"
  build:
    # Runs the job on a Ubuntu 20.04 virtual machine
    runs-on: ubuntu-20.04

    # Defines the steps in the job
    steps:
      # Checks out the repository code into the virtual machine
      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
            echo "tag=$(cat ./version.txt)" >> $GITHUB_ENV
      
       # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: confusb/hello-python # it will be lowercased internally
          image_tag: ${{ env.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}